# Generated by Django 5.2.10 on 2026-01-31 14:51

import SSS.models
import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('client', 'клиент'), ('builder', 'подрядчик')])),
                ('name', models.CharField(unique=True, verbose_name='контрагент')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='номер телефона')),
            ],
            options={
                'verbose_name': 'Контрагент',
                'verbose_name_plural': 'Контрагенты',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('boiler', 'котел'), ('manometer', 'манометр'), ('CGCP', 'газорегуляторный пункт шкафной')], verbose_name='тип оборудования')),
                ('name', models.CharField(unique=True, verbose_name='название')),
                ('verification_date', models.DateField(blank=True, null=True, verbose_name='дата поверки')),
                ('passport_scan', models.FileField(blank=True, null=True, upload_to=SSS.models.equipment_passport_path, verbose_name='скан паспорта')),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_opo', models.BooleanField(verbose_name='признак ОПО')),
                ('name', models.CharField(verbose_name='наименование ОПО')),
                ('address', models.CharField(verbose_name='адрес')),
                ('checking_frequency', models.CharField(verbose_name='периодичность объезда')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracted_objects', to='SSS.contractor')),
                ('equipment', models.ManyToManyField(to='SSS.equipment', verbose_name='оборудование')),
                ('responsible_from_builder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='builder_responsible_objects', to='SSS.contractor', verbose_name='ответственное лицо от ССС')),
                ('responsible_from_client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_responsible_objects', to='SSS.contractor', verbose_name='ответственное лицо от заказчика')),
            ],
            options={
                'verbose_name': 'Объект ОПО',
                'verbose_name_plural': 'Объекты ОПО',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('agreement', 'договор'), ('additional_agreement', 'доп. соглашение'), ('invoice', 'счет на оплату'), ('project', 'проект'), ('registration_certificate', 'свидетельство о регистрации')], max_length=100, verbose_name='тип документа')),
                ('number', models.BigIntegerField(blank=True, null=True, verbose_name='номер счета в бухгалтерской программе')),
                ('monthly', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='ежемесячные')),
                ('onetime', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='разовые')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='комментарии')),
                ('delivery_method', models.CharField(blank=True, max_length=100, null=True, verbose_name='способ отправки')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SSS.object', verbose_name='объект')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.CreateModel(
            name='ObjectRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_number', models.CharField(verbose_name='Регистрационный номер ОПО')),
                ('issued_at', models.DateField(blank=True, null=True, verbose_name='Дата регистрации')),
                ('is_active', models.BooleanField(default=True)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='SSS.object')),
            ],
        ),
    ]
